language: java

jdk:
  - oraclejdk8
  - openjdk8
  - openjdk9
  - openjdk11
  - openjdk12

  
os:
 - linux

# dist: trusty

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  