language: java

jdk:
  - oraclejdk8
# - oraclejdk9   removed since codecov required "mvn cobertura:cobertura" is not supported
  - openjdk12
  - openjdk9
  
os:
 - linux

dist: trusty

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  